// <auto-generated />
namespace Innobedded.KrankenHause.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init_Doctors_Krank : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_Doctors_Krank));
        
        string IMigrationMetadata.Id
        {
            get { return "202105281942110_init_Doctors_Krank"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
