// <auto-generated />
namespace Innobedded.KrankenHause.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ServiceTable_Und_ServiceReceptionTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ServiceTable_Und_ServiceReceptionTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202105282114404_ServiceTable_Und_ServiceReceptionTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
